/* ARCHIVO PRINCIPAL: edita equipos, horarios, graficas y links aqui */
export const DAYS = [
  { id: 'jun22', label: 'Lun 22', full: 'Lunes 22 de junio' },
  { id: 'jun23', label: 'Mar 23', full: 'Martes 23 de junio' },
  { id: 'jun24', label: 'Mié 24', full: 'Miércoles 24 de junio' },
  { id: 'jun25', label: 'Jue 25', full: 'Jueves 25 de junio' },
  { id: 'jun26', label: 'Vie 26', full: 'Viernes 26 de junio' },
  { id: 'jun27', label: 'Sáb 27', full: 'Sábado 27 de junio' },
];
export function flagUrl(code) { return `https://flagcdn.com/w80/${code.toLowerCase()}.png`; }
export const MATCHES = [
  // ═══ LUN 22 JUN (4) ═══
  {id:'arg-aut',day:'jun22',homeCode:'ar',awayCode:'at',home:'Argentina',away:'Austria',group:'Grupo J',time:'1:00 PM ET',venue:'AT&T Stadium, Arlington',
   graphs:{mcmc:'/graphs/jun22/arg_aut_mcmc.png',xgboost:'/graphs/jun22/arg_aut_xgboost.png',accuracy:'/graphs/jun22/arg_aut_accuracy.png', Resumen:'/graphs/jun22/arg_aut_resumen.png'},colabLink:'https://colab.research.google.com/drive/1uqA93_6P_GdtOq9XbtifmL0mSG0bm1nz?usp=sharing'},
  {id:'fra-irq',day:'jun22',homeCode:'fr',awayCode:'iq',home:'Francia',away:'Irak',group:'Grupo I',time:'5:00 PM ET',venue:'Lincoln Financial Field, Filadelfia',
   graphs:{mcmc:'/graphs/jun22/france_mcmc.png',xgboost:'/graphs/jun22/france_xgb.png',accuracy:'/graphs/jun22/france_accuracy.png', Resumen:'/graphs/jun22/france_resumen.png'},colabLink:'https://drive.google.com/file/d/14B6pa8sHNP4NnCdXeIQqOgiW7be2Ntcj/view?usp=sharing'},
  {id:'nor-sen',day:'jun22',homeCode:'no',awayCode:'sn',home:'Noruega',away:'Senegal',group:'Grupo I',time:'8:00 PM ET',venue:'MetLife Stadium, East Rutherford',
   graphs:{mcmc:'/graphs/jun22/nor_mcmc.png',xgboost:'/graphs/jun22/nor_xgb.png',accuracy:'/graphs/jun22/nor_accuracy.png', Resumen:'/graphs/jun22/nor_resumen.png'},colabLink:'https://drive.google.com/file/d/1TEAT_IEbTDgnhvEX2mSTPn-KMXhWzUu8/view?usp=sharing'},
  {id:'jor-alg',day:'jun22',homeCode:'jo',awayCode:'dz',home:'Jordania',away:'Argelia',group:'Grupo J',time:'11:00 PM ET',venue:"Levi's Stadium, Santa Clara",
   graphs:{mcmc:'/graphs/jun22/jor_mcmc.png',xgboost:'/graphs/jun22/jor_xgb.png',accuracy:'/graphs/jun22/jor_accuracy.png', Resumen:'/graphs/jun22/jor_resumen.png'},colabLink:'https://drive.google.com/file/d/11Mdx9BVZ1BmUAQoMdgBk9m6cHEKTUaEl/view?usp=sharing'},
  // ═══ MAR 23 JUN (4) ═══
  {id:'por-uzb',day:'jun23',homeCode:'pt',awayCode:'uz',home:'Portugal',away:'Uzbekistán',group:'Grupo K',time:'1:00 PM ET',venue:'NRG Stadium, Houston',
   graphs:{mcmc:'/graphs/jun23/por_mcmc.png',xgboost:'/graphs/jun23/por_xgb.png',accuracy:'/graphs/jun23/por_accuracy.png', Resumen:'/graphs/jun23/por_resumen.png'},colabLink:'https://drive.google.com/file/d/14mzn-UC80U5CB8ywTsyEKBeG1zzMhXRC/view?usp=sharing'},
  {id:'eng-gha',day:'jun23',homeCode:'gb-eng',awayCode:'gh',home:'Inglaterra',away:'Ghana',group:'Grupo L',time:'4:00 PM ET',venue:'Gillette Stadium, Foxborough',
   graphs:{mcmc:'/graphs/jun23/eng_mcmc.png',xgboost:'/graphs/jun23/eng_xgb.png',accuracy:'/graphs/jun23/eng_accuracy.png', Resumen:'/graphs/jun23/eng_resumen.png'},colabLink:'https://drive.google.com/file/d/1lL6wGDvnCXgHxayro8pcHD5IKquPk46B/view?usp=sharing'},
  {id:'pan-cro',day:'jun23',homeCode:'pa',awayCode:'hr',home:'Panamá',away:'Croacia',group:'Grupo L',time:'7:00 PM ET',venue:'BMO Field, Toronto',
    graphs:{mcmc:'/graphs/jun23/pan_mcmc.png',xgboost:'/graphs/jun23/pan_xgb.png',accuracy:'/graphs/jun23/pan_accuracy.png', Resumen:'/graphs/jun23/pan_resumen.png'},colabLink:'https://drive.google.com/file/d/1tLrgGDoHVyzFS-DA0CosRMkhq4W-_-0M/view?usp=sharing'},
  {id:'col-cod',day:'jun23',homeCode:'co',awayCode:'cd',home:'Colombia',away:'RD Congo',group:'Grupo K',time:'10:00 PM ET',venue:'Estadio Akron, Zapopan',
   graphs:{mcmc:'/graphs/jun23/col_mcmc.png',xgboost:'/graphs/jun23/col_xgb.png',accuracy:'/graphs/jun23/col_accuracy.png', Resumen:'/graphs/jun23/col_resumen.png'},colabLink:'https://drive.google.com/file/d/1TTM6_PjXQSbKd79p8j1KLwJlTYmlJJMr/view?usp=sharing'},
  // ═══ MIE 24 JUN (6) ═══
  {id:'sui-can',day:'jun24',homeCode:'ch',awayCode:'ca',home:'Suiza',away:'Canadá',group:'Grupo B',time:'3:00 PM ET',venue:'BC Place, Vancouver',
   graphs:{mcmc:'/graphs/jun24/can_mcmc.png',xgboost:'/graphs/jun24/can_xgb.png',accuracy:'/graphs/jun24/can_accuracy.png', Resumen:'/graphs/jun24/can_resumen.png'},colabLink:'https://drive.google.com/file/d/1QZ_81BcTv2jXDG5SwSU7t8fN5xdoEwSd/view?usp=sharing'},
  {id:'bih-qat',day:'jun24',homeCode:'ba',awayCode:'qa',home:'Bosnia y Herzegovina',away:'Catar',group:'Grupo B',time:'3:00 PM ET',venue:'Lumen Field, Seattle',
   graphs:{mcmc:'/graphs/jun24/bos_mcmc.png',xgboost:'/graphs/jun24/bos_xgb.png',accuracy:'/graphs/jun24/bos_accuracy.png', Resumen:'/graphs/jun24/bos_resumen.png'},colabLink:'https://drive.google.com/file/d/1lTF6X_DUBkdM3GSTTlCa1dV8gloVdU5l/view?usp=sharing'},
  {id:'sco-bra',day:'jun24',homeCode:'gb-sct',awayCode:'br',home:'Escocia',away:'Brasil',group:'Grupo C',time:'6:00 PM ET',venue:'Hard Rock Stadium, Miami Gardens',
   graphs:{mcmc:'/graphs/jun24/sco_mcmc.png',xgboost:'/graphs/jun24/sco_xgb.png',accuracy:'/graphs/jun24/sco_accuracy.png', Resumen:'/graphs/jun24/sco_resumen.png'},colabLink:'https://drive.google.com/file/d/1MHs9i1ZYxzJrrtszpFm0Hk0E_USqeGit/view?usp=sharing'},
  {id:'mar-hai',day:'jun24',homeCode:'ma',awayCode:'ht',home:'Marruecos',away:'Haití',group:'Grupo C',time:'6:00 PM ET',venue:'Mercedes-Benz Stadium, Atlanta',
   graphs:{mcmc:'/graphs/jun24/mor_mcmc.png',xgboost:'/graphs/jun24/mor_xgb.png',accuracy:'/graphs/jun24/mor_accuracy.png', Resumen:'/graphs/jun24/mor_resumen.png'},colabLink:'https://drive.google.com/file/d/1KujBMPxjyF4sUtHYqLatZUQmbf469GFk/view?usp=sharing'},
  {id:'cze-mex',day:'jun24',homeCode:'cz',awayCode:'mx',home:'Chequia',away:'México',group:'Grupo A',time:'9:00 PM ET',venue:'Estadio Azteca, Ciudad de México',
   graphs:{mcmc:'/graphs/jun24/mex_mcmc.png',xgboost:'/graphs/jun24/mex_xgb.png',accuracy:'/graphs/jun24/mex_accuracy.png', Resumen:'/graphs/jun24/mex_resumen.png'},colabLink:'https://drive.google.com/file/d/1qoKLaVrXmQ7sqBLiavXmC9lkDCQzdK30/view?usp=sharing'},
  {id:'rsa-kor',day:'jun24',homeCode:'za',awayCode:'kr',home:'Sudáfrica',away:'Corea del Sur',group:'Grupo A',time:'9:00 PM ET',venue:'Estadio BBVA, Monterrey',
   graphs:{mcmc:'/graphs/jun24/sou_mcmc.png',xgboost:'/graphs/jun24/sou_xgb.png',accuracy:'/graphs/jun24/sou_accuracy.png', Resumen:'/graphs/jun24/sou_resumen.png'},colabLink:'https://drive.google.com/file/d/1I4LATy3A66rQFBQJV2Nup3yTeoHAW3xF/view?usp=sharing'},
  // ═══ JUE 25 JUN (6) ═══
  {id:'ecu-ger',day:'jun25',homeCode:'ec',awayCode:'de',home:'Ecuador',away:'Alemania',group:'Grupo E',time:'4:00 PM ET',venue:'MetLife Stadium, East Rutherford',
   graphs:{mcmc:'/graphs/jun25/ecu_mcmc.png',xgboost:'/graphs/jun25/ecu_xgb.png',accuracy:'/graphs/jun25/ecu_accuracy.png', Resumen:'/graphs/jun25/ecu_resumen.png'},colabLink:'https://drive.google.com/file/d/1-Wiu_icCQiYRN0oM2hH8d_OC8bk2D6VW/view?usp=sharing'},
  {id:'cur-civ',day:'jun25',homeCode:'cw',awayCode:'ci',home:'Curazao',away:'Costa de Marfil',group:'Grupo E',time:'4:00 PM ET',venue:'Lincoln Financial Field, Filadelfia',
   graphs:{mcmc:'/graphs/jun25/cur_mcmc.png',xgboost:'/graphs/jun25/cur_xgb.png',accuracy:'/graphs/jun25/cur_accuracy.png', Resumen:'/graphs/jun25/cur_resumen.png'},colabLink:'https://drive.google.com/file/d/1pONrroHu7p7iDqDIkqDuFHnXp-43OaD1/view?usp=sharing'},
  {id:'jpn-swe',day:'jun25',homeCode:'jp',awayCode:'se',home:'Japón',away:'Suecia',group:'Grupo F',time:'7:00 PM ET',venue:'AT&T Stadium, Arlington',
   graphs:{mcmc:'/graphs/jun25/jap_mcmc.png',xgboost:'/graphs/jun25/jap_xgb.png',accuracy:'/graphs/jun25/jap_accuracy.png', Resumen:'/graphs/jun25/jap_resumen.png'},colabLink:'https://drive.google.com/file/d/1DomT5lnN8TNqKQq8VihEOfW2EQr1lDmW/view?usp=sharing'},
  {id:'tun-ned',day:'jun25',homeCode:'tn',awayCode:'nl',home:'Túnez',away:'Países Bajos',group:'Grupo F',time:'7:00 PM ET',venue:'Arrowhead Stadium, Kansas City',
   graphs:{mcmc:'/graphs/jun25/tun_mcmc.png',xgboost:'/graphs/jun25/tun_xgb.png',accuracy:'/graphs/jun25/tun_accuracy.png', Resumen:'/graphs/jun25/tun_resumen.png'},colabLink:'https://drive.google.com/file/d/167jHU7C9T8i7DgCBzw9wpGow-u1_NyNo/view?usp=sharing'},
  {id:'tur-usa',day:'jun25',homeCode:'tr',awayCode:'us',home:'Turquía',away:'Estados Unidos',group:'Grupo D',time:'10:00 PM ET',venue:'SoFi Stadium, Inglewood',
   graphs:{mcmc:'/graphs/jun25/usa_mcmc.png',xgboost:'/graphs/jun25/usa_xgb.png',accuracy:'/graphs/jun25/usa_accuracy.png', Resumen:'/graphs/jun25/usa_resumen.png'},colabLink:'https://drive.google.com/file/d/15wSPoU6lknPGBnQYaRobYEd3Rhj03crs/view?usp=sharing'},
  {id:'par-aus',day:'jun25',homeCode:'py',awayCode:'au',home:'Paraguay',away:'Australia',group:'Grupo D',time:'10:00 PM ET',venue:"Levi's Stadium, Santa Clara",
   graphs:{mcmc:'/graphs/jun25/par_mcmc.png',xgboost:'/graphs/jun25/par_xgb.png',accuracy:'/graphs/jun25/par_accuracy.png', Resumen:'/graphs/jun25/par_resumen.png'},colabLink:'https://drive.google.com/file/d/1SNR2eXvdQ8CClPgOH7dVhOUwWW49UFxQ/view?usp=sharing'},
  // ═══ VIE 26 JUN (6) ═══
  {id:'nor-fra',day:'jun26',homeCode:'no',awayCode:'fr',home:'Noruega',away:'Francia',group:'Grupo I',time:'3:00 PM ET',venue:'Gillette Stadium, Foxborough',
   graphs:{mcmc:'/graphs/jun26/nor_mcmc.png',xgboost:'/graphs/jun26/nor_xgb.png',accuracy:'/graphs/jun26/nor_accuracy.png', Resumen:'/graphs/jun26/nor_resumen.png'},colabLink:'https://drive.google.com/file/d/1zSmmai5GeT-lFEK4jMn8-RGn2itg-VXa/view?usp=sharing'},
  {id:'sen-irq',day:'jun26',homeCode:'sn',awayCode:'iq',home:'Senegal',away:'Irak',group:'Grupo I',time:'3:00 PM ET',venue:'BMO Field, Toronto',
   graphs:{mcmc:'/graphs/jun26/sen_mcmc.png',xgboost:'/graphs/jun26/sen_xgb.png',accuracy:'/graphs/jun26/sen_accuracy.png', Resumen:'/graphs/jun26/sen_resumen.png'},colabLink:'https://drive.google.com/file/d/12yBuo99DKzYHur4iC2FTwZUl3Kew28Xf/view?usp=sharing'},
  {id:'cpv-sau',day:'jun26',homeCode:'cv',awayCode:'sa',home:'Cabo Verde',away:'Arabia Saudita',group:'Grupo G',time:'8:00 PM ET',venue:'NRG Stadium, Houston',
   graphs:{mcmc:'/graphs/jun26/cap_mcmc.png',xgboost:'/graphs/jun26/cap_xgb.png',accuracy:'/graphs/jun26/cap_accuracy.png', Resumen:'/graphs/jun26/cap_resumen.png'},colabLink:'https://drive.google.com/file/d/1pTY2hltDVy1uwdmb_qVL_ce0osDUOgO_/view?usp=sharing'},
  {id:'uru-esp',day:'jun26',homeCode:'uy',awayCode:'es',home:'Uruguay',away:'España',group:'Grupo G',time:'8:00 PM ET',venue:'Estadio Akron, Zapopan',
   graphs:{mcmc:'/graphs/jun26/uru_mcmc.png',xgboost:'/graphs/jun26/uru_xgb.png',accuracy:'/graphs/jun26/uru_accuracy.png', Resumen:'/graphs/jun26/uru_resumen.png'},colabLink:'https://drive.google.com/file/d/1Zy__b2fEbuVOf5kItnnhTd6-61V8ya_H/view?usp=sharing'},
  {id:'egy-irn',day:'jun26',homeCode:'eg',awayCode:'ir',home:'Egipto',away:'Irán',group:'Grupo H',time:'11:00 PM ET',venue:'Lumen Field, Seattle',
   graphs:{mcmc:'/graphs/jun26/egy_mcmc.png',xgboost:'/graphs/jun26/egy_xgb.png',accuracy:'/graphs/jun26/egy_accuracy.png', Resumen:'/graphs/jun26/egy_resumen.png'},colabLink:'https://drive.google.com/file/d/16I7kO7_6h-hvhVt54RipzM9EaaWI4jU-/view?usp=sharing'},
  {id:'nzl-bel',day:'jun26',homeCode:'nz',awayCode:'be',home:'Nueva Zelanda',away:'Bélgica',group:'Grupo H',time:'11:00 PM ET',venue:'BC Place, Vancouver',
   graphs:{mcmc:'/graphs/jun26/new_mcmc.png',xgboost:'/graphs/jun26/new_xgb.png',accuracy:'/graphs/jun26/new_accuracy.png', Resumen:'/graphs/jun26/new_resumen.png'},colabLink:'https://drive.google.com/file/d/1jwA0ivLSIJYfNqxypI-l7lbQYvAusqgX/view?usp=sharing'},
  // ═══ SAB 27 JUN (6) ═══
  {id:'pan-eng',day:'jun27',homeCode:'pa',awayCode:'gb-eng',home:'Panamá',away:'Inglaterra',group:'Grupo L',time:'5:00 PM ET',venue:'MetLife Stadium, East Rutherford',
   graphs:{mcmc:'/graphs/jun27/pan_mcmc.png',xgboost:'/graphs/jun27/pan_xgb.png',accuracy:'/graphs/jun27/pan_accuracy.png', Resumen:'/graphs/jun27/pan_resumen.png'},colabLink:'https://drive.google.com/file/d/19q05b9yGn3WhX8ZMKcworyrTI3h0iCLt/view?usp=sharing'},
  {id:'cro-gha',day:'jun27',homeCode:'hr',awayCode:'gh',home:'Croacia',away:'Ghana',group:'Grupo L',time:'5:00 PM ET',venue:'Lincoln Financial Field, Filadelfia',
   graphs:{mcmc:'/graphs/jun27/cro_mcmc.png',xgboost:'/graphs/jun27/cro_xgb.png',accuracy:'/graphs/jun27/cro_accuracy.png', Resumen:'/graphs/jun27/cro_resumen.png'},colabLink:'https://drive.google.com/file/d/1QL5PwcvM-v1-kzMLvvJFJ-H_Vp3db5me/view?usp=sharing'},
  {id:'col-por',day:'jun27',homeCode:'co',awayCode:'pt',home:'Colombia',away:'Portugal',group:'Grupo K',time:'7:30 PM ET',venue:'Hard Rock Stadium, Miami Gardens',
   graphs:{mcmc:'/graphs/jun27/col_mcmc.png',xgboost:'/graphs/jun27/col_xgb.png',accuracy:'/graphs/jun27/col_accuracy.png', Resumen:'/graphs/jun27/col_resumen.png'},colabLink:'https://drive.google.com/file/d/1LqufLYbOAgEIkX5sHs5p7NgLwzq8qe6h/view?usp=sharing'},
  {id:'cod-uzb',day:'jun27',homeCode:'cd',awayCode:'uz',home:'RD Congo',away:'Uzbekistán',group:'Grupo K',time:'7:30 PM ET',venue:'Mercedes-Benz Stadium, Atlanta',
   graphs:{mcmc:'/graphs/jun27/drc_mcmc.png',xgboost:'/graphs/jun27/drc_xgb.png',accuracy:'/graphs/jun27/drc_accuracy.png', Resumen:'/graphs/jun27/drc_resumen.png'},colabLink:'https://drive.google.com/file/d/11i3LVH3Dy0Mb8v3EoXSkeC4c3kDTblXH/view?usp=sharing'},
  {id:'alg-aut',day:'jun27',homeCode:'dz',awayCode:'at',home:'Argelia',away:'Austria',group:'Grupo J',time:'10:00 PM ET',venue:'Arrowhead Stadium, Kansas City',
   graphs:{mcmc:'/graphs/jun27/arg_mcmc.png',xgboost:'/graphs/jun27/arg_xgb.png',accuracy:'/graphs/jun27/arg_accuracy.png', Resumen:'/graphs/jun27/arg_resumen.png'},colabLink:'https://drive.google.com/file/d/1pDS2idTj0cOiFjr7v2FAphz8pKwboKtm/view?usp=sharing'},
  {id:'jor-arg',day:'jun27',homeCode:'jo',awayCode:'ar',home:'Jordania',away:'Argentina',group:'Grupo J',time:'10:00 PM ET',venue:'AT&T Stadium, Arlington',
   graphs:{mcmc:'/graphs/jun27/jor_mcmc.png',xgboost:'/graphs/jun27/jor_xgb.png',accuracy:'/graphs/jun27/jor_accuracy.png', Resumen:'/graphs/jun27/jor_resumen.png'},colabLink:'https://drive.google.com/file/d/1y768uI2Kizm9wbijznAsVWEB2xLc8WXX/view?usp=sharing'},
];
export function getMatchesByDay(dayId) { return MATCHES.filter(m => m.day === dayId); }
export function getMatchById(matchId) { return MATCHES.find(m => m.id === matchId); }
